Modify load scripts

diff --git a/scull/scull_load b/scull/scull_load
--- a/scull/scull_load
+++ b/scull/scull_load
@@ -1,5 +1,5 @@
 #!/bin/sh
-# $Id: scull_load,v 1.4 2004/11/03 06:19:49 rubini Exp $
+
 module="scull"
 device="scull"
 mode="664"
@@ -11,9 +11,23 @@ else
     group="wheel"
 fi
 
+# Root or die
+if [ "$(id -u)" != "0" ]
+then
+  echo "You must be root to load or unload kernel modules"
+  exit 1
+fi
+
+kernel_ver=$(uname -r)
+module_dir="/lib/modules/$kernel_ver/updates"
+if [ ! -d "$module_dir" ]; then
+    echo "Module directory not found: $module_dir"
+    exit 1
+fi
+
 # invoke insmod with all arguments we got
 # and use a pathname, as insmod doesn't look in . by default
-insmod ./$module.ko $* || exit 1
+insmod $module_dir/$module.ko $* || exit 1
 
 # retrieve major number
 major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
